feat(ch. 05): introduction to custom block state property
TeamCovertDragon/Harbinger pull request #25
Opened 2019-06-18 09:16 UTC by 3TUSK

## Synopsis / 简介

Close GH-22: 介绍如何创建并使用自定义 `IProperty`。

## Description / 详细说明

见上。

## Justification / 理由

见 GH-22。

## Remarks / 备注

N/A

2019-06-21 02:21 UTC, SeraphJACK commented
下次你推 test 分支吧，这样有 preview 看。

2019-06-21 02:33 UTC, 3TUSK commented
Test 分支上有 #24。

2019-06-24 07:52 UTC, SeraphJACK commented
~~其实这个你也忘记 request review 了~~

2019-06-24 10:16 UTC, SeraphJACK requested changes

2019-06-24 10:16 UTC, SeraphJACK commented on chapter-05/block-state.md
> +  - `BlockHorizontal.FACING` 是一个 `PropertyDirection`，允许的值有 `EnumFacing.EAST`、`EnumFacing.SOUTH`、`EnumFacing.WEST` 和 `EnumFacing.NORTH`，用于描述仅能绕 Y 轴作“水平方向上的”旋转的方块的朝向。
`UP` 和 `DOWN` 呢

2019-06-24 10:16 UTC, SeraphJACK commented on chapter-05/block-state.md
> +    public Optional<String> parseValue(String value) {
com.google.common.base.Optional

2019-06-24 10:20 UTC, SeraphJACK commented on chapter-05/block-state.md
> +    public Optional<String> parseValue(String value) {
最好注明这个import，不过idea有inspection..很奇怪

2019-07-07 23:10 UTC, 3TUSK commented
@SeraphJACK 本 PR 的预览已可以[在这里查看](https://mc-modding.tritusk.info/epsilon/trigger/preview/25/)。

2019-07-08 02:51 UTC, SeraphJACK approved these changes

2019-07-09 07:30 UTC, merged

2019-07-09 07:31 UTC, 3TUSK commented
关于方块状态和模型之间的对应关系（即 `IStateMapper` 和 BlockState JSON）将统一由 #26 处理。