Close GH-4: add a list of recommended mod source code for reference
TeamCovertDragon/Harbinger pull request #34
Opened 2019-08-01 11:57 UTC by 3TUSK

## Synopsis / 简介

Close GH-4。

## Description / 详细说明

添加一份推荐参考的 Mod 源码列表。

## Justification / 理由

见 GH-4。

## Remarks / 备注

N/A

2019-08-01 15:30 UTC, SeraphJACK reviewed
要不要把 Pro Con 两个词改成大多数人看得懂的（

2019-08-01 22:18 UTC, 3TUSK commented
倒是换成什么啊……

2019-08-02 00:06 UTC, SeraphJACK commented
我也不知道啊(跑

2019-08-02 04:34 UTC, Snownee commented
不是很明白为什么要推荐CraftTweaker

2019-08-02 04:41 UTC, 3TUSK commented
@Snownee 总有人问如何删合成。

2019-08-02 04:57 UTC, SeraphJACK approved these changes

2019-08-02 04:57 UTC, Snownee commented
> @Snownee 总有人问如何删合成。

因为你问了如何删合成，所以请把整个 CraftTweaker 源码看了？

2019-08-02 05:00 UTC, SeraphJACK commented
> 因为你问了如何删合成，所以请把整个 CraftTweaker 源码看了？

1. 没必要看整个源码
2. 这是推荐参考模组列表，全面一点没什么坏处
3. CraftTweaker 里的确有很多可以参考

- 添加/删除各种 recipe
- Mod 兼容
- 加载脚本

2019-08-02 05:16 UTC, Snownee commented
> 添加/删除各种 recipe
Mod 兼容
加载脚本

正因为脚本引擎和那套基于注解的系统使得它不适合作为一个模组来推荐。你说匠魂有前置不方便看，那 CraftTweaker 就方便看了吗？

2019-08-02 05:23 UTC, 3TUSK commented
> 正因为脚本引擎和那套基于注解的系统使得它不适合作为一个模组来推荐。
有趣。那么问题出现了，如果我不把 CraftTweaker 作为一个 Mod 来推荐，而是推荐它的某一小部分呢？

2019-08-02 05:26 UTC, Snownee commented
> 有趣。那么问题出现了，如果我不把 CraftTweaker 作为一个 Mod 来推荐，而是推荐它的某一小部分呢？

我没意见。不过如果仅仅是删除配方那部分的话，不如直接推荐 Cuisine 好了，更加直观不是吗？

2019-08-02 05:27 UTC, 3TUSK commented
> 不如直接推荐 Cuisine 好了

我从 Charset 学来的。

2019-08-02 05:27 UTC, SeraphJACK commented
~~所以其实你就是来安利 Cuisine 的~~

加上我没意见

2019-08-02 05:30 UTC, Snownee commented
> ~~所以其实你就是来安利 Cuisine 的~~

不我只是举了个我知道的例子。既然 3T 说是从 Charset 学来的，那么我觉得显然 Charset 更合适了。另外我不推荐看 Cuisine 的代码。

2019-08-02 05:31 UTC, 3TUSK commented
其实还可以单列一个国产 Mod 列表，这样还有中文注释可以看。

2019-08-02 05:31 UTC, Snownee commented
> 其实还可以单列一个国产 Mod 列表

指有中文注释的国产 Mod

2019-08-02 05:32 UTC, SeraphJACK commented
国产 Mod 也不一定是中文注释吧

2019-08-02 05:42 UTC, 3TUSK commented
> 国产 Mod 也不一定是中文注释吧

酒石酸写的都是。

2019-08-02 05:44 UTC, TartaricAcid commented
我写中文注释目的是为了可能会有国人想要学习相关的代码，或者帮忙查找 bug，如果要改成英文倒也可以……

2019-08-02 05:50 UTC, 3TUSK commented
> 擦我没 at 人啊

------

> 可能会有国人想要学习相关的代码

看，这便是中文注释存在的价值

2019-08-02 05:52 UTC, liach commented
个人表示反对……你还不如直接让用户去找 github 上的 minecraft 标签

2019-08-02 05:54 UTC, Snownee commented on chapter-31/index.md
> +    - 优势：LGPL v3 授权
LGPL 也成优势了吗……

2019-08-02 06:25 UTC, 3TUSK commented on chapter-31/index.md
> +    - 优势：LGPL v3 授权
相比楼下 IE 那个自己写的 license 已经是谢天谢地了

2019-08-02 06:42 UTC, 3TUSK commented
@liach 
我现在推荐的几个 Mod 中，这几个完全没有任何标签：

  - https://github.com/BluSunrize/ImmersiveEngineering
  - https://github.com/CraftTweaker/CraftTweaker
  - https://github.com/ForestryMC/ForestryMC
  - https://github.com/SlimeKnights/TinkersConstruct

我应该会把 CraftTweaker 去掉换上 Twilight Forest。即便如此，五个推荐的 Mod 里有三个没有任何标签。

此外，有 `minecraft` 标签的不一定是基于 Forge 的 Mod，比如：

  - SpongeAPI：https://github.com/SpongePowered/SpongeAPI 
  - Paper：https://github.com/PaperMC/Paper
  - Cuberite（一个 C++ 写的 Minecraft 服务器端）https://github.com/cuberite/cuberite
  - 甚至是 HMCL：https://github.com/huanghongxun/HMCL
  - 哦还有 MultiMC：https://github.com/MultiMC/MultiMC5

2019-08-14 05:25 UTC, SeraphJACK commented
要不要提醒一下 LICENSE 的问题?

2019-08-14 07:05 UTC, 3TUSK commented
@SeraphJACK 之前是有的，我后来想了想去掉了……

2019-08-15 02:14 UTC, SeraphJACK requested changes

2019-08-15 02:14 UTC, SeraphJACK commented on chapter-31/index.md
> +
还是提醒一下 LICENSE 防止有人复制粘贴吧

2019-08-15 02:15 UTC, SeraphJACK commented on chapter-31/index.md
> +
不用每个列出来，在前面提醒一下注意每个项目的 LICENSE 问题不要直接复制粘贴就好了

2019-08-15 04:52 UTC, SeraphJACK approved these changes

2019-08-15 07:52 UTC, merged