Rewrite TileEntity and Capability articles
TeamCovertDragon/Harbinger pull request #53
Opened 2019-11-16 22:34 UTC by 3TUSK

## Synopsis / 简介

重写 TileEntity 和 Capability 相关章节。

## Description / 详细说明

 - TileEntity 重写
   - 引入具体案例（`MyLavaFurnaceEntity`）。
   - 引入 `ITickable` 概念。
 - Capability 从第 28 章提前至第 10 章，原第 10 章（附魔相关）并入第 4 章（物品）。
 - Capability 章节拆分：所有具体的 Capability 接口分散至相应的章节，第 10 章仅保留 `IItemHandler` 的讲解作为示范，与第 9 章（TileEntity）相关对接。
   - `IFluidHandler` 相关并入第 26 章（Forge 流体系统）。
   - `IAnimationStateMachine` 并入第 11 章（渲染概论）。
   - `IEnergyStorage` 待定。

## Justification / 理由

  1. 不重写基本没人看懂
  2. 已知反馈中，多数认为 Capability 一章太过靠后，对新人不甚友好
  3. 咕太久了

## Remarks / 备注

I dunno.

2019-11-16 23:09 UTC, 3TUSK commented
TODO：把 #36 写的东西都搬过来

2019-11-23 06:19 UTC, Snownee requested changes

2019-11-23 06:19 UTC, Snownee commented on chapter-04/enchantment.md
> +```
建议添加 `isTreasureEnchantment` 方法的解释。

2019-11-23 06:19 UTC, Snownee commented on chapter-04/enchantment.md
> +通常，附魔的效果和附魔本身的类没有关系。举个例子，精准采集和时运的逻辑实际上是在 `Block` 里的。还记得 Forge patch 后的那个获得掉落的方法 `getDrops` 吗？它最后一个 `int` 参数就是当前使用工具的时运等级。
`onEntityDamaged` `onUserHurt`

2019-11-23 06:19 UTC, Snownee commented on chapter-09/index.md
> +TileEntity 也可以像 Entity 一样，通过[实现 `ITickable` 接口](ticking.md)来获得每秒刷新 20 次的能力。
这句话有歧义。

2019-11-23 06:19 UTC, Snownee commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
一点疑问：给自己的类加`final`是好习惯吗？

2019-11-23 06:19 UTC, Snownee commented on chapter-09/index.md
> +                return true;
多余的返回。

2019-11-23 06:19 UTC, Snownee commented on chapter-09/index.md
> +     * @return true if it is accepted as fuel and thus consumed
为什么这里又不用中文了？

2019-11-23 06:19 UTC, Snownee commented on chapter-09/index.md
> +        }
鉴于这里还没有讲到流体系统，不如直接判断手持的是否为熔岩桶，以方便理解。

顺带一提，`IFluidHandler.drain`无法保证抽取的流体一定为1桶。

2019-11-23 06:19 UTC, Snownee commented on chapter-09/ticking.md
> +        }
与前文同样的问题。

2019-11-23 06:19 UTC, Snownee commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
既然每tick都会被执行一次，又有何必要死循环呢？

2019-11-23 06:19 UTC, Snownee commented on chapter-10/attach-cap.md
> +                    return  CapabilityItemHandler.ITEM_HANDLER_CAPABILITY.cast(...);
多了一个空格。

2019-11-23 06:21 UTC, 3TUSK commented on chapter-04/enchantment.md
> +```
不是这个 PR 的覆盖范围，但是记下了。

2019-11-23 06:21 UTC, 3TUSK commented on chapter-04/enchantment.md
> +通常，附魔的效果和附魔本身的类没有关系。举个例子，精准采集和时运的逻辑实际上是在 `Block` 里的。还记得 Forge patch 后的那个获得掉落的方法 `getDrops` 吗？它最后一个 `int` 参数就是当前使用工具的时运等级。
不是这个 PR 的覆盖范围，但是记下了。

2019-11-23 06:22 UTC, 3TUSK commented on chapter-09/index.md
> +TileEntity 也可以像 Entity 一样，通过[实现 `ITickable` 接口](ticking.md)来获得每秒刷新 20 次的能力。
请解释

2019-11-23 06:22 UTC, 3TUSK commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
如果你不需要继承的话。

2019-11-23 06:23 UTC, 3TUSK commented on chapter-09/index.md
> +     * @return true if it is accepted as fuel and thus consumed
意识流。已标记。

2019-11-23 06:24 UTC, 3TUSK commented on chapter-09/index.md
> +        }
1. Accepted
2. 那我可以检查返回值.jpg

2019-11-23 06:24 UTC, 3TUSK commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
你可能没见过真的有在这个方法里 `for (int i = 0; i < 20; i++)` 的人

2019-11-23 06:25 UTC, 3TUSK commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
你可能没见过真的在这里写循环 20 次的人……

2019-11-23 06:25 UTC, 3TUSK commented on chapter-04/enchantment.md
> +通常，附魔的效果和附魔本身的类没有关系。举个例子，精准采集和时运的逻辑实际上是在 `Block` 里的。还记得 Forge patch 后的那个获得掉落的方法 `getDrops` 吗？它最后一个 `int` 参数就是当前使用工具的时运等级。
不是这个 PR 的覆盖范围，但是记下了。

2019-11-23 06:28 UTC, Snownee commented on chapter-09/index.md
> +TileEntity 也可以像 Entity 一样，通过[实现 `ITickable` 接口](ticking.md)来获得每秒刷新 20 次的能力。
通过令 TileEntity [实现 `ITickable` 接口](ticking.md)，可以让其像实体一样拥有每秒刷新 20 次的能力。

2019-11-23 06:31 UTC, Snownee commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
如果别人想写个附属呢？

2019-11-23 06:32 UTC, Snownee commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
个例不能代表普遍问题。

2019-11-23 06:54 UTC, 3TUSK commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
倒不如说这么写就是防个例用的……

2019-11-24 00:58 UTC, liach commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
别人可以直接用AT

2019-11-24 01:09 UTC, liach commented on chapter-09/index.md
> +TileEntity 也可以像 Entity 一样，通过[实现 `ITickable` 接口](ticking.md)来获得每秒刷新 20 次的能力。
都讲到这种概念了，“刻”应该提早讲

2019-11-24 01:09 UTC, liach commented on chapter-09/index.md
> +                return true;
isRemote要放到instanceof后，这样玩家手动作才会正确渲染。instanceof成功返回 true，失败返回false

2019-11-24 01:09 UTC, liach commented on chapter-09/ticking.md
> +        // 那样会导致游戏假死。
实际上在任何mod用的地方（除了自己开特殊线程吧）都不应该死循环

2019-11-24 06:24 UTC, Snownee commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
@liach 怎么用？

2019-11-24 07:06 UTC, 3TUSK commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
`public-f`。不过我挺怀疑有这个必要吗……

2019-11-24 11:29 UTC, Snownee commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
我一直以为AT只能用在MCP

2019-11-24 16:00 UTC, liach commented on chapter-09/index.md
> +public final class MyLavaFurnace extends Block {
不过你给别的mod用at在1.12要在`build.gradle`加`deobfMcp(deobfSrg) { failOnAtError = false }` [见此处](https://github.com/AlmuraDev/Almura/blob/da9ab088ca248e1fbf32344482c1ea3a96350de8/build.gradle#L64-L65) 不然构建会炸

2019-11-26 20:34 UTC, liach commented on chapter-09/index.md
> +        } else {
最好不要在return语句后面加 else语句（原版有是fernflower的问题，实际写尽量不要这样写，代码会不清晰）

2019-11-28 07:06 UTC, Snownee approved these changes

2019-11-28 07:38 UTC, 3TUSK commented on chapter-09/index.md
> +        } else {
~~为什么我之前认为这样会产生不一样的字节码？~~

2019-11-28 07:44 UTC, liach approved these changes

2019-11-28 08:04 UTC, liach commented on chapter-10/index.md
> +将功能转化为可反复使用的零件，用作某一个更大的“实体”（可以是狭义上的实体、TileEntity 甚至是物品）的基础，同时避免过强的耦合。
:+1:

2019-11-29 04:28 UTC, SeraphJACK requested changes

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-04/enchantment.md
> +    event.getRegistry().registerAll(new MyPowerfulEnchantment().setName("super_duper_enchantment").setRegistryName(...));
`MyPowerfulEnchantment` 没有零参构造器，虽然这不影响但还是统一一下？

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-09/index.md
>  @SubscibreEvent
typo

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-09/index.md
> +    }
少写了 `getFuel` 方法

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-09/ticking.md
> +}
一样少写了 `getFuel` 方法

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/attach-cap.md
> +        })
少了个分号（（（

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +            if (inventory.getItemInSlot(0).isEmpty()) {
`getStackInSlot` instead of `getItemInSlot`

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +                        entity.setItem(inventory.insertItem(entity.getItem(), 0, false));
第一个和第二个参数反了

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +                    inventory.insertItem(FurnaceRecipes.instance().getSmeltingResult(inventory.getItemInSlot(0).copy(), 1, false));
```java
inventory.insertItem(1, FurnaceRecipes.instance().getSmeltingResult(inventory.getStackInSlot(0).copy()), false);
```

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +    private final ItemStackHandler inventory = new ItemStackHandler(2);
没有写序列化和反序列化

2019-11-29 04:28 UTC, SeraphJACK commented on SUMMARY.md
> +  * [10.4 你自己的 Capability](chapetr-10/new-cap.md)
typo

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +        public void readNBT(Capability<PowerContainer> cap, PowerContainer instance, NBTBase data, EnumFacing side) {
参数错误

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +    CapabilityManager.register(PowerContainer.class, new IStorage<PowerContainer>() {
`CapabilityManager.INSTANCE.register`

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +    CapabilityManager.register(PowerContainer.class, new IStorage<PowerContainer>() {
`Capability.IStorage`

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
`((NBTTagString)data).getString()`

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +    })
分号

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-27/container/block.md
> +    public IFluidTankProperties[] getTanksProperties() {
`getTankProperties`

2019-11-29 04:28 UTC, SeraphJACK commented on chapter-27/container/item.md
>  import net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack;
1. `@Override`
2. `FluidHandlerItemStack` 构造器不对

2019-11-29 05:49 UTC, 3TUSK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
事实证明这里可以直接 `getString` 无需 cast……

2019-11-29 05:51 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
你开 AT 了吧，我这里 access 有问题

2019-11-29 05:54 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
![Screenshot_20191129_135342](https://user-images.githubusercontent.com/25274081/69846650-aaa8fe00-12af-11ea-8f8d-6d774f3d6ece.png)

```
minecraft_version=1.12.2
forge_version=14.23.5.2815
mapping_version=stable_39
```

2019-11-29 05:56 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
~~所以其实直接 `toString` 也行~~

2019-11-29 06:00 UTC, 3TUSK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
草，好吧

2019-11-29 06:01 UTC, SeraphJACK commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
不，你追踪一下就发现 toString 也不对

2019-11-29 06:01 UTC, 3TUSK commented on chapter-04/enchantment.md
> +    event.getRegistry().registerAll(new MyPowerfulEnchantment().setName("super_duper_enchantment").setRegistryName(...));
不是这个 PR 的覆盖范围，但是记下了。

2019-11-29 06:05 UTC, 3TUSK commented on chapter-09/index.md
> +    }
`getFuel`?

2019-11-29 06:29 UTC, 3TUSK commented on chapter-09/ticking.md
> +}
实际上是压根儿没有 `fuel` 字段……

2019-11-29 06:35 UTC, 3TUSK commented on chapter-09/index.md
> +    }
好吧，发现了……

2019-11-29 07:43 UTC, liach commented on chapter-10/new-cap.md
> +                instance.setPower(new BigInteger(data.getString()));
toString我记得写的是可以直接当snbt的内容（指令里打的nbt）

2019-11-29 10:24 UTC, SeraphJACK requested changes

2019-11-29 10:24 UTC, SeraphJACK commented on chapter-09/index.md
> +        return fuel.getItem() == Items.LAVA_BUCKET ? ItemStack.EMPTY : fuel;
为什么是返回空而不是空桶？

2019-11-29 16:41 UTC, 3TUSK commented on chapter-09/index.md
> +        return fuel.getItem() == Items.LAVA_BUCKET ? ItemStack.EMPTY : fuel;
草，写错了

2019-11-30 04:36 UTC, SeraphJACK requested changes

2019-11-30 04:36 UTC, SeraphJACK commented on chapter-09/index.md
> +    public ItemStack tryAcceptFuel(ItemStack fuel) {
是不是忘记加 `this.fuel` 了...

2019-11-30 04:36 UTC, SeraphJACK commented on chapter-09/ticking.md
> +    public ItemStack tryAcceptFuel(ItemStack fuel) {
同上

2019-11-30 04:36 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +然而目前的例子还是有问题。我们很快就会发现：通过使用漏斗等设备，我们指定的输出格也可以放进去物品。我们不能直接将 `ItemStackHandler` 暴露出来，而是通过一个“中间人”来完成。将 `getCapability` 方法改成这样：
还有个问题，破坏方块的时候没有把 `IItemHandler` 里的物品全部加入掉落..

2019-11-30 04:49 UTC, 3TUSK commented on chapter-10/item-cap.md
> +然而目前的例子还是有问题。我们很快就会发现：通过使用漏斗等设备，我们指定的输出格也可以放进去物品。我们不能直接将 `ItemStackHandler` 暴露出来，而是通过一个“中间人”来完成。将 `getCapability` 方法改成这样：
甚至加入掉落，能不写吗.jpg

2019-11-30 05:22 UTC, 3TUSK commented on chapter-09/index.md
> +    public ItemStack tryAcceptFuel(ItemStack fuel) {
草

2019-11-30 05:50 UTC, SeraphJACK commented on chapter-10/item-cap.md
> +    public void breakBlock(World world, BlockPos pos, IBlockState state) {
`world.isRemote` ？

2019-11-30 05:52 UTC, SeraphJACK approved these changes

2019-11-30 06:17 UTC, merged