feat(index,ch.39,ch.40): practices are here today
TeamCovertDragon/Harbinger pull request #63
Opened 2020-02-10 23:35 UTC by 3TUSK

## Synopsis / 简介

Harbinger 系列练习题。

## Description / 详细说明

追加一系列 Mod 开发中的真实案例以供读者参考和练习。

## Justification / 理由

每一个读者偏好的学习方式不尽相同：有些能直接看说明书就知道该怎么写，有些喜欢看视频，有些更适合听别人讲，还有人需要看实例代码……  
这个 PR 的目标正是为 Harbinger（及它的后续版本）写作范式的多样化铺平道路。

## Remarks / 备注

欢迎投稿！

2020-02-11 00:19 UTC, SeraphJACK commented
![Screenshot_20200211_081846](https://user-images.githubusercontent.com/25274081/74202349-27405b80-4ca7-11ea-8ec9-30e6460f3d06.png)

这玩意点开之后长这样....

2020-02-11 00:20 UTC, SeraphJACK requested changes
md 文件没有被 parse

2020-02-11 00:29 UTC, SeraphJACK requested changes

2020-02-11 00:29 UTC, SeraphJACK commented on chapter-40/practice-1.md
> +  - 右击打开 GUI，可从中取走所有物品，但当所有物品全部取出时物品直接消失（即 `isEmpty() == true`）
说明右键时生成战利品？

2020-02-11 00:29 UTC, SeraphJACK commented on chapter-40/practice-6.md
> +    - 一颗末影珍珠可保持该 TileEntity 所在区块及周围 3x3 区块加载 12 小时，以现实时间计算。
注明是 ticks / 20 ，而不是 “现实时间”？考虑低 tps 的情况

2020-02-11 00:29 UTC, SeraphJACK commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
这个提示建议删掉

2020-02-11 00:31 UTC, 3TUSK commented on chapter-40/practice-6.md
> +    - 一颗末影珍珠可保持该 TileEntity 所在区块及周围 3x3 区块加载 12 小时，以现实时间计算。
我需要查一下 Railcraft 使用的究竟是哪个时间。游戏里标称“小时”其实不怎么可靠……

2020-02-11 00:31 UTC, 3TUSK commented on chapter-40/practice-1.md
> +  - 右击打开 GUI，可从中取走所有物品，但当所有物品全部取出时物品直接消失（即 `isEmpty() == true`）
生成的时机其实无所谓，掉落时就生成好或者右击打开时再生成都可以。

2020-02-11 00:33 UTC, 3TUSK commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
理由？

2020-02-11 00:37 UTC, SeraphJACK commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
这里是 “没有答案” 的实战，我认为应该要求对象具有自己想办法实现这个特性的能力。

2020-02-11 00:40 UTC, SeraphJACK commented on chapter-40/practice-6.md
> +    - 一颗末影珍珠可保持该 TileEntity 所在区块及周围 3x3 区块加载 12 小时，以现实时间计算。
https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java#L258

2020-02-11 03:34 UTC, liach commented on chapter-40/practice-6.md
> +    - 一颗末影珍珠可保持该 TileEntity 所在区块及周围 3x3 区块加载 12 小时，以现实时间计算。
当然用tick，只是假设没有sponge的entity activation等魔法机制，20tick为一秒

2020-02-11 03:35 UTC, liach commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
实际上这里按照railcraft的写不一定最好，可以考虑把加载器存在玩家附属信息或者世界信息中，不要带坏新手

2020-02-11 03:37 UTC, liach commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
建议改成`用一种可持续的方法识别、寻找玩家，不受改名、盗版等影响`

2020-02-11 04:04 UTC, 3TUSK commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
> 不受改名、盗版等影响

我个人是认为应该不管盗版的，所以玩家的 UUID 其实是最好的选择。

2020-02-11 04:05 UTC, Snownee commented on chapter-40/practice-1.md
> +  - 任意怪物（这里限定为 `instanceof EntityMob`）死亡时低概率掉落
“低概率掉落”是通过什么判断的？配置文件？

2020-02-11 04:05 UTC, Snownee commented on chapter-40/practice-2.md
> +  - 根据方块所在位置确定刷怪类型，并利用容器中的剑模拟怪物被击杀并掉落物品的过程
需要详细解释。

2020-02-11 04:05 UTC, Snownee commented on chapter-40/practice-2.md
> +  - 会将收集到的怪物掉落放入旁边的容器中
与装剑的容器是同一个吗？剑是否会消耗耐久？掉落物是否受剑附魔影响？

2020-02-11 04:05 UTC, Snownee commented on chapter-40/practice-4.md
> +  - 喝水可以恢复口渴值。
水瓶？

2020-02-11 06:02 UTC, liach commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
实际上盗版UUID也是可以持续的，好像是盗版用户名前面加`OfflineUser:`然后生成UUID

2020-02-11 08:46 UTC, SeraphJACK commented on chapter-40/practice-1.md
> +  - 任意怪物（这里限定为 `instanceof EntityMob`）死亡时低概率掉落
只是作为练习的话，这里并不需要太在意吧（

2020-02-11 10:34 UTC, Yesterday17 commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
```java
UUID.nameUUIDFromBytes(("OfflinePlayer:" + name).getBytes(StandardCharsets.UTF_8))
````

2020-02-11 10:36 UTC, Yesterday17 commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
服务器开关 online-mode / 玩家修改昵称会使任意一种简单的解决方案出现问题

2020-02-12 01:55 UTC, SeraphJACK commented on chapter-40/practice-6.md
> +      - 可通过 `EntityPlayer.getUniqueID()` 拿到玩家的 UUID。
开关 online-mode 还是自己想办法解决吧...

2020-02-13 00:20 UTC, SeraphJACK requested changes

2020-02-13 00:20 UTC, SeraphJACK commented on chapter-40/index.md
> +  - [Railcraft 界钉（Worldspike，即原世界锚 World Anchor）][q6]
问题7呢？

2020-02-13 00:24 UTC, 3TUSK commented on chapter-40/index.md
> +  - [Railcraft 界钉（Worldspike，即原世界锚 World Anchor）][q6]
_草_

2020-02-13 05:16 UTC, Snownee approved these changes

2020-02-13 05:17 UTC, Snownee commented on chapter-40/practice-7.md
> +  - 可直接看到储罐内部存储的流体。
应当支持发光流体以及气体

2020-02-16 04:29 UTC, Snownee commented
@3TUSK 暮色森林传送门要安排上吗？

2020-03-30 23:32 UTC, NanamiArihara commented on chapter-40/practice-7.md
> +  - 可直接看到储罐内部存储的流体。
应当支持 The One Probe，Waila/Hwyla 的流体显示

2020-03-31 01:50 UTC, 3TUSK commented on chapter-40/practice-7.md
> +  - 可直接看到储罐内部存储的流体。
_你不说我都快忘了这里还有个 PR……_

2021-03-26 15:25 UTC, SeraphJACK approved these changes

2021-03-26 15:25 UTC, merged